<a href="https://colab.research.google.com/github/shoiTK/deep_learning_with_pytorch/blob/main/first_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from __future__ import print_function　#旧バージョンで新バージョンのモジュールを使用するため
import torch

# Getting start

In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[4.0462e-36, 0.0000e+00, 1.6675e-43],
        [5.6052e-44, 1.6816e-43, 6.1657e-44],
        [4.4842e-44, 1.6956e-43, 6.1657e-44],
        [4.4842e-44, 1.7096e-43, 5.7453e-44],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3087, 0.3605, 0.1189],
        [0.6216, 0.2037, 0.0188],
        [0.6899, 0.8007, 0.8313],
        [0.3534, 0.8866, 0.1053],
        [0.9833, 0.8949, 0.3242]])


In [12]:
x = torch.zeros(5, 3, dtype=torch.long)
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [10]:
x = torch.tensor([5, 3])
print(x)

tensor([5, 3])


In [21]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.5474, 0.3750, 0.9432],
        [0.7498, 0.1984, 0.5679],
        [0.6843, 0.1508, 0.8850],
        [0.4232, 0.7671, 0.0973],
        [0.9071, 0.6690, 0.0027]])


In [17]:
x = torch.ones(5, 3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [22]:
print(x.size())

torch.Size([5, 3])


In [36]:
y = torch.rand(5, 3)
x = torch.rand(5, 3)
print(x, y, x + y, sep='\n\n', end='\n\n')
print(torch.add(x, y))

tensor([[0.5635, 0.1528, 0.4255],
        [0.0629, 0.1170, 0.2707],
        [0.9656, 0.8252, 0.4341],
        [0.6671, 0.5090, 0.9488],
        [0.5554, 0.2093, 0.7504]])

tensor([[0.3537, 0.8634, 0.5667],
        [0.9911, 0.5249, 0.6322],
        [0.6734, 0.7808, 0.2411],
        [0.3773, 0.1850, 0.7578],
        [0.6197, 0.9374, 0.3652]])

tensor([[0.9172, 1.0163, 0.9922],
        [1.0540, 0.6419, 0.9030],
        [1.6390, 1.6061, 0.6752],
        [1.0445, 0.6940, 1.7065],
        [1.1751, 1.1466, 1.1156]])

tensor([[0.9172, 1.0163, 0.9922],
        [1.0540, 0.6419, 0.9030],
        [1.6390, 1.6061, 0.6752],
        [1.0445, 0.6940, 1.7065],
        [1.1751, 1.1466, 1.1156]])


In [37]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.9172, 1.0163, 0.9922],
        [1.0540, 0.6419, 0.9030],
        [1.6390, 1.6061, 0.6752],
        [1.0445, 0.6940, 1.7065],
        [1.1751, 1.1466, 1.1156]])


In [39]:
y.add_(x)
print(y)

tensor([[0.9172, 1.0163, 0.9922],
        [1.0540, 0.6419, 0.9030],
        [1.6390, 1.6061, 0.6752],
        [1.0445, 0.6940, 1.7065],
        [1.1751, 1.1466, 1.1156]])


In [40]:
print(x[:,1])

tensor([0.1528, 0.1170, 0.8252, 0.5090, 0.2093])


In [45]:
x = torch.randn(4, 4)
y = x.view(16)
print(y)
z = x.view(-1, 8)
print(z)

tensor([ 0.5740, -0.5326, -0.9027, -0.9160, -1.2941,  0.3826, -0.6640, -0.0383,
        -0.3631,  0.1357,  1.8956,  0.8531,  0.5251,  1.2199, -2.4411,  0.3651])
tensor([[ 0.5740, -0.5326, -0.9027, -0.9160, -1.2941,  0.3826, -0.6640, -0.0383],
        [-0.3631,  0.1357,  1.8956,  0.8531,  0.5251,  1.2199, -2.4411,  0.3651]])


In [46]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.0155])
0.01547191757708788


# Numpy Brigde

In [48]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [49]:
 b = a.numpy()
 print(b)

[1. 1. 1. 1. 1.]


In [50]:
a.add_(1)
print(a, b, sep='\n')

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [52]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a, b)

[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# CUDA tensor

In [3]:
import torch
x = torch.ones(5)
if torch.cuda.is_available():
  device = torch.device("cuda")
  y = torch.ones_like(x, device=device)
  x = x.to(device)
  z = x + y
  print(z)
  print(z.to("cpu", torch.double))

tensor([2., 2., 2., 2., 2.], device='cuda:0')
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
